name: schedule

on:
  schedule:
    - cron: '*/10 * * * *'  # Minden 10. percben

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run cron job
      run: php path/to/your/script.php